Djembe/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
#from ajax_select import urls as ajax_select_urls
admin.autodiscover()
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Djembe.views.home', name='home'),
    # url(r'^Djembe/', include('Djembe.foo.urls')),

    url(r'^tracker/',include('tracker.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
 #   url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','Djembe.views.index'),
    url(r'^about/','Djembe.views.about'),
    url(r'^music/',include('plugins.music.urls')),
    url(r'^movies/',include('plugins.movies.urls')),
    url(r'^ajax/',include('ajax.urls')),
    url(r'^profile/',include('userprofile.urls')),
    url(r'^user/$','userprofile.views.view'),
    url(r'^users/(?P<username>[\w]+)','userprofile.views.view'),
    url(r'^accounts/',include('invitation.urls')),
    url(r'^accounts/', include('registration.urls')),
    url(r'^forums/',include('forum.urls')),
    url(r'^torrent/',include('torrent.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root':settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT}),
)

ajax/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('ajax.views',
    url(r'^$','index'),
    url(r'^unique/$','checkUnique'),
    url(r'^previewpost/$','postPreview'),
    url(r'^editpost/$','editPost'),
    url(r'^getIds/$','getIds'),
)

plugins/music/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('plugins.music.views',
    url(r'^artists/$', 'artistsIndex'),
    url(r'^artists/new/$','addArtist'),
    url(r'^artists/(?P<artist_id>\d+)/$', 'artistPage'),
    url(r'^artists/(?P<artist_id>\d+)/edit/$', 'editArtist'),
    url(r'^artists/(?P<artist_id>\d+)/new/$', 'addAlbum'),
    url(r'^albums/$','albumsIndex'),
    url(r'^albums/(?P<album_id>\d+)/$', 'albumPage'),
    url(r'^albums/(?P<album_id>\d+)/addtag/$', 'addTag'),
    url(r'^albums/(?P<album_id>\d+)/(?P<tag_id>\d+)/(?P<action>\w+)','tagVote'),
    url(r'^albums/(?P<album_id>\d+)/add/$','addRelease'),
    url(r'^releases/(?P<release_id>\d+)/add/$','addFormat'),
)

plugins/music/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from forum.models import Post
from tags.models import Tag, TagCount, TagVote
from photo.models import Photo
from django.db.models.signals import m2m_changed
from django.dispatch import receiver

import torrent
from torrent.models import Torrent

RELEASE_TYPE = (
    ("album","Album"),
    ("ep","EP"),
    ("single","Single"),
    ("compilation","Compilation"),
    ("anthology","Anthology"),
)

FORMATS = (
    ("mp3","MP3"),
    ("flac","FLAC"),
)

BITRATES = (
    ("320","320"),
    ("lossless","Lossless"),
)

MEDIAS = (
    ("cd","CD"),
)

VOTES = (
    (-1,"down"),
    (1,"up"),
)

class Album(models.Model):
    artists = models.ManyToManyField('Artist')
    #releases = models.ManyToManyField('Release',blank=True,related_name='album')
    name = models.CharField(max_length=100)
    released = models.IntegerField('Year released')
    tags = models.ManyToManyField(TagCount)
    photos = models.ManyToManyField(Photo,blank=True)
    releaseType = models.CharField(max_length=15,choices=RELEASE_TYPE,default="album")
    albumInfo = models.TextField(blank=True,null=True)
    comments = models.ManyToManyField(Post,editable=False)

    @models.permalink
    def get_absolute_url(self):
        return ('plugins.music.views.albumPage',[str(self.id)])

    def save(self,*args,**kwargs):
        super(Album,self).save(*args,**kwargs)
        if not self.releases.all():
            original = Release.objects.create(year=self.released,title="Original Release",album=self)
            original.save()

    def __unicode__(self):
        return self.name

@receiver(m2m_changed, sender=Album.artists.through)
def verify_uniqueness(sender, **kwargs):
    album = kwargs.get('instance', None)
    action = kwargs.get('action', None)
    artists = kwargs.get('pk_set', None)

    if action == 'pre_add':
        for artist in artists:
            if Album.objects.filter(name=album.name).filter(artists=artist):
                raise IntegrityError('Album with name %s already exists for artist %s' % (album.name, Artist.objects.get(pk=artist)))


class Artist(models.Model):
    name = models.CharField(max_length=100)
    artistInfo = models.TextField(blank=True,null=True,verbose_name='Artist Info')
    photo = models.ManyToManyField(Photo,blank=True)

    def taglist(self):
        tags = dict()
        for album in self.album_set.all():
            album_tags = album.tags.all()
            for tag in album_tags:
                if tag.tag.name in tags:
                    tags[tag.tag.name] += 1
                else:
                    tags[tag.tag.name] = 1
        tags = tags.items()
        tags.sort(key=lambda tup:tup[1],reverse=True)
        return tags

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('plugins.music.views.artistPage',[str(self.id)])



class Label(models.Model):
    name = models.CharField(max_length=100,unique=True)

    def __unicode__(self):
        return self.name

class Release(models.Model):
    album = models.ForeignKey(Album,related_name="releases")
    label = models.ForeignKey(Label, null=True,blank=True)
    catalogNumber = models.CharField(max_length=100,blank=True,verbose_name="Catalog Number")
    year = models.IntegerField()
    title = models.CharField(max_length=100,blank=True)
    torrents = models.ManyToManyField(Torrent,through='AlbumFormat',blank=True,null=True)
    class Meta:
        unique_together = ('album','label','year','catalogNumber')
        unique_together = ('album','year','catalogNumber')

    def format(self):
        formatted = str(self.year)
        if self.title:
            formatted += " / "+self.title
        if self.label:
            formatted += " / "+str(self.label)
        if self.catalogNumber:
            if not self.label:
                formatted += " / "
            else:
                formatted += " "
            formatted += self.catalogNumber
        return formatted

    def __unicode__(self):
        return self.album.name+": "+self.format()

class AlbumFormat(models.Model):
    release = models.ForeignKey('Release')
    torrent = models.ForeignKey(Torrent)
    format = models.CharField(max_length=5,choices=FORMATS)
    bitrate = models.CharField(max_length=10,choices=BITRATES)
    media = models.CharField(max_length=2,choices=MEDIAS)

    def fileName(self):
        return self.release.album.name+" ("+str(self.release.album.released)+") ["+self.format.upper()+"]"


"""
class TagVotes(models.Model):
    tag = models.ForeignKey('TagCount')
    user = models.ForeignKey(User)
    way = models.IntegerField(choices=VOTES,default=1)

class TagCount(models.Model):
    album = models.ForeignKey(Album)
    tag = models.ForeignKey(Tag, related_name="tag_name")
    count = models.IntegerField(default=0)
    voters = models.ManyToManyField(User,through=TagVotes)

    class Meta:
        ordering = ['-count','tag']

    def __unicode__(self):
        return self.album.name+":"+self.tag.name

    def save(self, *args, **kwargs):
        self.count = self.getCount()
        super(TagCount,self).save(*args,**kwargs)

    def getCount(self):
        count = 15
        votes = self.tagvotes_set.aggregate(count=Sum('way'))['count']
        if votes: count += votes
        return count"""

plugins/music/forms.py
from itertools import chain
from optparse import _
from django import forms
from django.core.exceptions import ValidationError
from django.db.models.fields import TextField
from django.forms import ModelForm
from django.forms.formsets import BaseFormSet
from django.forms.widgets import Widget
from django.forms.util import flatatt
from django.forms.widgets import TextInput
from django.utils import simplejson
from django.utils.encoding import force_unicode, smart_unicode
from django.utils.safestring import mark_safe
from django.utils.html import escape, conditional_escape
from django.utils.translation import ugettext_lazy as _
from django.core.validators import EMPTY_VALUES
from django.contrib.auth.models import User
from taggit.forms import TagField

from models import *

class ArtistForm(ModelForm):
    class Meta:
        model = Artist
        exclude = ('photo')

class MultipleTextFieldWidget(Widget):
    class Media:
        js = ('scripts/multitextfield.js',)

    def render(self, name, value, attrs=None,choices=()):
        inputs = "<div class='multitext' value='"+name+"'><input class='choices' type='hidden' value='"+simplejson.dumps(dict(self.choices))+"' />"
        inputs += "[<a class='remove' href='#'> - </a>][<a class='add' href='#'> + </a>]<br/><br/>"
        #options = self.render_textfields(choices, value)
        #print options
        labels = dict(self.choices)
        #print labels
        for val in value:
            inputs += "<input name='"+name+"Name' type='text' value='"+str(labels[int(val)])+"'/>"
            inputs += "<input name='"+name+"' type='hidden' value='"+str(val)+"' /><br/>"
        #inputs +="<input class='return' name='"+name+"' type='hidden' value=''/>"
        #print inputs
        return mark_safe(inputs+"</div>")

class MultipleTextField(forms.models.ModelMultipleChoiceField):
    widget = MultipleTextFieldWidget
    pass

class LazyChoiceField(forms.ChoiceField):
    def __init__(self, *args, **kwargs):
        super(LazyChoiceField, self).__init__(*args, **kwargs)

    def valid_value(self, value):
        return True

class ArtistNameForm(forms.Form):
    name = forms.CharField()
    id = LazyChoiceField(required=False)
    def __init__(self,*args,**kwargs):
        initial = kwargs.get('initial',{})
        choices = initial.get('choices')
        super(ArtistNameForm,self).__init__(*args,**kwargs)
        if choices:
            self.fields['id'].choices = choices
            if len(choices) == 1:
                self.fields['id'].widget.attrs['style'] = "display:none"

class BaseArtistNameFormSet(BaseFormSet):
    def add_fields(self, form, index):
        super(BaseArtistNameFormSet,self).add_fields(form,index)
        form.fields['id'].widget.attrs['class']="span1"



class AlbumForm(ModelForm):
    def __init__(self,*args, **kwargs):
        super(AlbumForm,self).__init__(*args,**kwargs)
        #print self.fields['artists']
        #self.fields['artists'] = MultipleTextField(Artist.objects)
        #print self.fields['artists']
    class Meta:
        model = Album
        exclude = ('photos','tags','artists')
        widgets = {
            #'artists':MultipleTextFieldWidget()
        }

class ReleaseForm(ModelForm):
    label = forms.CharField(required=False)

    class Meta:
        model = Release
        exclude = ('torrents','label')

        widgets = (
            {'album':forms.HiddenInput()}
        )

class FormatForm(ModelForm):
    class Meta:
        model = AlbumFormat
        exclude = ('torrent')
        widgets = (
            {'release':forms.HiddenInput()}
        )

templates/music/artists/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
        <form action="" method="POST" class="form-stacked">
            {% csrf_token %}
            {{form.as_p}}
            <div class="actions">
                <input type="submit" class="btn primary"/>
            </div>
        </form>
{% endblock %}

templates/music/artists/index.html
{% extends "base.html" %}
{% block content %}
    <div class="page-header">
        <h3>Artists</h3>
    </div>
    <div class="pull-right">
        <ul class="linkbox">
            <li>[<a href="{%url plugins.music.views.addArtist %}">New Artist</a>]</li>
        </ul>
    </div>
    {% if artists %}
        <table>
            <tr class="colhead">
                <td>Name</td>
                <td>#Albums</td>
                <td>Time</td>
            </tr>
            {% for artist in artists %}
                <tr>
                    <td>
                        <a href="{% url plugins.music.views.artistPage artist_id=artist.id%}">{{ artist.name }}</a>
                        <ul class="flatlist">
                         {%comment%}   {% if artist.album_set.all %}
                                {% for album in artist.album_set.all %}
                                    <li><a href="{%url plugins.music.views.albumPage album_id=album.id%}">{{ album}}</a></li>
                                    {% if album.tags.all %}
                                        <h6>Tags</h6>
                                        <ul>
                                            {% for tag in album.tags.all %}
                                                <li>{{ tag.name }}</li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                {% endfor %}

                        {% else %}
                            <li>no albums</li>
                        {% endif %}{%endcomment%}
                            {% for tag,count in artist.taglist %}
                                <li>{{tag}}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{artist.album_set.count}}</td>
                    <td>{{artist.sort|timesince}} ago</td>
                </tr>
            {%  endfor %}
        </table>
    {%  else %}
        No artists available.
    {% endif %}
{% endblock %}

templates/music/artists/new.html
{% extends "base.html" %}
{% load i18n %}
{% load add_class %}
{% block content %}
        <div class="row">
        <form action="" method="POST" class="form-stacked span10 offset2" id="newartistform">
            {% csrf_token %}
            {% for field in form %}
                <div class="clearfix">
                    {{field.errors}}
                    {{field.label_tag}}
                    <div class="input">
                        {{field|add_class:'span8'}}
                    </div>
                </div>
            {% endfor %}
            <div class="actions">
                <input id="submitArtist" type="submit" class="btn primary" name='newartist'"/>
                <input id="submitArtistAndAddAlbum" type="submit" class="btn" name="newartistandalbum" value="Submit and add album" />
            </div>
        </form>
        </div>
        <div id="modal-warning" class="modal hide fade in" style="display: none; ">
            <div class="modal-header">
                <a href="#" class="close">×</a>
                <h3>Warnings</h3>
            </div>
            <div class="modal-body">
                <p>Do you want to submit anyways?</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn primary" onclick="$('#modal-warning').modal('hide')">No</a>
                <span class="btn secondary" onclick="$('#newartistform').unbind('submit');$('#newartistform #submitArtist').click()">Yes</span>
            </div>
        </div>
        <script>
            $("form").submit(function (e) {
               if ($(e.target).children(".warning").length>0 && $("#modal-warning").css("display") == "none") {
                    $("#modal-warning").modal({
                        backdrop:true,
                        show:true
                    })
                    return false;
               } else {
                   return true;
               }

            });
           checkUnique($("#id_name"),"artists")
        </script>
{% endblock %}

templates/music/artists/viewArtist.html
{% extends "base.html" %}

{% block content %}
    <script>
        function toggleRelease(id,c,e) {
            if (c.innerHTML=="+") {
                c.innerHTML = "-";
                $(".release"+id).removeClass("releaseCollapsed");
            } else {
                c.innerHTML = "+";
                $(".release"+id).addClass("releaseCollapsed");
            }
        }
        function toggleGroup(id,c,e) {
            if (c.className=="show_torrents"){
                c.className="hide_torrents";
                $(".group"+id).removeClass("groupCollapsed")
            }
            else {
                c.className="show_torrents";
                $(".group"+id).addClass("groupCollapsed")
            }
        }
        function toggleReleaseType(type) {
            if (!$(".release_"+type).is(".tableCollapsed")) {
                $(".release_"+type).addClass("tableCollapsed");
            } else {
                $(".release_"+type).removeClass("tableCollapsed");
            }
        }
    </script>
    <div class="page-header">
        <h3>{{artist.name}}</h3>
    </div>
    <div class="pull-right">
        <ul class="linkbox">
            <li>[<a href="{%url plugins.music.views.editArtist artist_id=artist.id%}">Edit</a>]</li>
            <li>[<a href="{%url plugins.music.views.addAlbum artist_id=artist.id%}">Add Album</a>]</li>
        </ul>
    </div>
    <div class="clear"></div>
    <div class="row">
        <div class="main span9">
        <div class="releaseTypeBox">
            {% for releaseType,typeAlbums in albums.items %}
                {% if typeAlbums %}
                    <a href="#{{releaseType}}Table">{{releaseType}}s</a>
                {% endif %}
            {% endfor %}
        </div>
        {% for releaseType,typeAlbums in albums.items %}
            {% if typeAlbums %}
                <div class="releaseType" id="{{releaseType}}Table">
                    <table>
                        <tr class="colhead">
                            <td class="collapser"></td>
                            <td>
                                {{releaseType}}s
                                <a href="#" onclick="toggleReleaseType('{{releaseType}}');return false;">(View)</a>
                            </td>
                            <td class="size">Size</td>
                            <td class="stat">&#8635;</td>
                            <td class="stat">&uArr;</td>
                            <td class="stat">&dArr;</td>
                        </tr>

                        {% for album in typeAlbums %}
                            <tr class="release_{{releaseType}} group">
                                <td><a href="#" onclick="toggleGroup({{album.id}},this,event);return false;" class="show_torrents"></a></td>
                                <td colspan="5">
                                    <h3 class="pull-left">{{album.released}} - <a href="{%url plugins.music.views.albumPage album_id=album.id%}">{{album.name}}</a></h3>
                                    <span class="pull-right">[<a href="{%url plugins.music.views.addRelease album_id=album.id%}">Add release</a>]</span>
                                    <div class="clear"></div>
                                    {% for tag in album.tags.all %}
                                        {{tag}}{% if not forloop.last %}, {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                            {% for release in album.releases.all %}
                                <tr class="release_{{releaseType}} groupCollapsed group{{album.id}}">
                                    <td colspan="6">
                                        <span class="pull-left">
                                            {% if release.albumformat_set.all %}
                                                <a href="#" onclick="toggleRelease({{release.id}},this,event);return false;">+</a>
                                            {% endif %}
                                            <strong>{{release.format}}</strong>
                                        </span>
                                        <span class="pull-right">[<a href="{%url plugins.music.views.addFormat release_id=release.id%}">Add format</a>]</span>
                                        <span class="clear"></span>
                                    </td>
                                </tr>
                                {% for format in release.albumformat_set.all %}
                                    <tr class="release_{{releaseType}} groupCollapsed group{{album.id}} releaseCollapsed release{{release.id}}">
                                        <td colspan="2">
                                            » {{format.format|upper}} / {{format.bitrate|capfirst}}
                                            <span class="pull-right">
                                                [
                                                <a href="{%url torrent.views.get format.torrent.id%}">DL</a>
                                                ]
                                            </span>
                                        </td>
                                        <td>
                                            {{format.torrent.size|filesizeformat}}
                                        </td>
                                        <td>
                                            {{format.torrent.downloaded}}
                                        </td>
                                        <td>
                                            {{format.torrent.seeders}}
                                        </td>
                                        <td>
                                            {{format.torrent.leechers}}
                                        </td>
                                    </tr>
                                {% endfor %}

                            {% endfor %}
                        {% endfor %}
                    </table>
                </div>
            {% endif %}
        {% endfor %}
        <div class="box">
            <div class="head">Artist Info</div>
            <div class="pad">
                {{artist.artistInfo}}
            </div>
        </div>
    </div>
        <div class="sidebar span3">
        {% if artist.photo.all %}
            <div class="box">
                <div class="head">
                    {{artist}}
                </div>
                <div class="pad">
                    <img src="{{artist.photo.get.name}}"/>
                </div>
            </div>
        {% else %}
            <div class="box">
                <div class="head">Add Image</div>
                <div class="pad">
                    <form action="" method="POST" class="form-stacked" style="padding-left: 0">
                        {% csrf_token %}
                        {{photoForm.as_p}}
                        <input type="submit" class="btn primary"/>
                    </form>
                </div>
            </div>
        {% endif %}
        {% if artist.taglist %}
            <div class="box">
                <div class="head">Tags</div>
                <div class="pad">
                    {% for tag, count in artist.taglist %}
                        {{tag}} ({{count}})<br/>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="box">
            <div class="head">
                Statistics
            </div>
            <div class="pad">
                <ul>
                    <li>Number of groups: {{artist.album_set.count}}</li>
                    <li>Number of torrents: {{artist.torrent__count}}</li>
                    <li>Number of seeders: {{artist.seeders}}</li>
                    <li>Number of leeches: {{artist.leechers}}</li>
                    <li>Number of snatches: {{artist.snatches}}</li>
                </ul>
            </div>
        </div>

    </div>
    </div>
{% endblock %}